--- 
layout: post
title: RubyConf Day 1
---
I love conferences.  I'm sitting in the hotel bar with almost a dozen "caboosers":http://caboo.se, it's good company.  

I arrived last night with a slight alcohol buzz from drinking with Kevin and "Rick":http://www.rickbradley.com on the plane.  This is my second conference so it was dope to hop out of the cab and see "Ezra":http://brainspl.at outside the hotel smoking.  Dropped my stuff off in the hotel and mingled for a few hours with random hackers and acquaintances.  Crashed out around 4am to be up at 8:30 for breakfast.  After a tasty breakfast I realized what I was in the middle of, a collection of some of the brightest minds in our community, the vibe here is nothing but positive.  It's nice to see something more ruby focused and less focused on rails exclusively.  There's definitely an air of dissatisfaction among quite a few people here with rails currently, perhaps something cooler will come along sooner than we'd thought.

Today's talks were pretty pimp.  Takahashi's talk covered the history of ruby which gave a little more background than I'd collected in the past.  Apparently the name Coral was considered at the time Ruby was chosen. :)  Evan Phoenix gave a cool talk on Sydney/Rubinius.  He's basically been developing a way write the ruby compiler in ruby.  His code sampler were really cool w/ how he's doing module inclusion and he also showed off how the vm looks.

I saw this kid there who looked strangely familiar.  I suddenly realized I knew him from about 10 or 11 years ago.  He's the brother of this guy I used to skate with back in the day.  Strangely enough we've been in the same irc channel for about a year and never figure out who each other were.  It was dope that he remembered me and we shot the shit about people I hadn't thought about in years.  So I ate the tasty provided lunch with Gianni/Yipstar and all was chill.

After lunch talks were really cool.  "Geoffrey":http://www.topfunky.com, "Kevin":http://glutton.us, and "Zed":http://www.zedshaw.com gave great talks.  Geoffrey covered graphics in rails, it pretty well covered everything from graphing to image manipulation.  He had links to a couple projects I'd never seen before which was a pleasant surprise.  Kevin gave a talk on his Google Summer of Code project, "mkrf":http://mkrf.rubyforge.org.  I originally didn't think it'd be that interesting, but he did a fabulous job presenting the material.  Zed went into his RFuzz library and testing/profiling with it.  His approach to things and his very interesting(yet honest) perspectives on programmers was really great.  Unfortunately I bailed on John Long's talk, mainly because I wasn't interested in radiant that much, and the first few minutes consisted of him installing radiant....

Other than that I now have a dvorak keyboard layout thanks to indirect showing me how to pull my keys safely.  Now to see how long it takes before I switch.  The hardest part for me is putting my hands down on the keyboard and not having the little risers to let me know where my home keys are.  Dvorak here I come?
